#!/usr/bin/env bash
# Checking for command-line argument
if [ $# -lt 4 ]
then
	  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	    exit 1
fi

#declaring argument variable

file_path=$1
ipadd=$2
username=$3
ssh_path=$4


# disabbling Strict Host Key
scp -o "StrictHostKeyChecking no" -i "$ssh_path" "$file_path" "$username@$ipadd:~/"

# Checking if the transfer was successful
if [ $? -eq 0 ]
then
	  echo "FILE TRANSFER WAS SUCCESSFULL"
  else
	    echo "FILE TRANSFER FAILED"
fi
