#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path=$1
ipaddress=$2
username=$3
shh_path=$4

# disabling the strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$shh_path" "file_path" "$username@$ipaddress:~/"

#check file transfer
if [$? -eq 0]
then
	echo "FILE TRANSFERED SUCCESSFULLY"
else
	echo "FILE TRANFER FAILED"
fi
