#!/usr/bin/env bash
# configuration of web-01 to have an http response header

#  update and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# create index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# working on a "moved permanently redirection" (301)
new_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/channel\/UCXKOaa6_MaCEBaCkfYn8fWg permanent;"
#create similar server config
sudo sed -i "s/server_name _;/$new_str/" /etc/nginx/sites-enabled/default

# Create 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

# Listen on port 80 as default port
sudo sed -i "s/listen 80 default_server;/$new_str/" /etc/nginx/sites-enabled/default

# create http response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# restart nginx after implementing changes
sudo service nginx restart
