#!/usr/bin/env bash
# Create a scrit that install and configure HAproxy on your lb-01 server
# After which the scrit also send trafic to server web-01 and web-02
# Then distribute the request using roundrobing algorithm
# Also allow the scrit to start by init scrit

# First update and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo tee /etc/haproxy/haproxy.cfg >/dev/null <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server server1 54.227.222.216:80 check
    server server2 100.26.152.71:80 check
EOL

# scrit that enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# now let test the haproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
# Ok restart the service
sudo service haproxy restart
