#!/usr/bin/env bash
# bash scrip that 
# Create the file /var/run/myscript.pid
# Display "To infinity and beyond" indefinitely
# Display "I hate the kill command" when receiving SIGTERM signal
# Display "Y u no love me?!" when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminate itself

trap high_2 SIGTERM
trap high_3 SIGINT
trap high_1 SIGQUIT

high_1()
{
  rm -rf /var/run/myscript.pid
  exit
}

high_2()
{
  echo "I hate the kill command"
  high_1
}

high_3()
{
  echo "Y U no love me?!"
}

echo $$ > /var/run/myscript.pid

while (( 1 ))
do
	echo "To infinity and beyond"
	sleep 2
done
