#!/usr/bin/env bash
# Bash script that displays
# "To infinity and beyond" indefinitely
# with a sleep in between each iteration
# "I am invincible!!!" when receiving a SIGTERM signal

trap highlander SIGTERM

highlander()
{
  echo "I am invincible!!!"
}

while (( 1 ))
do
	echo "To infinity and beyond"
	sleep 2
done
