#!/usr/bin/env bash
# Script that display numbers from 1 to 100
# Displays FizzBuzz if number is multiple of 3 and 5
# Fizz when number is multiple of 2
# Buzz whe number is multiple of 5
# else display number

for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done
