#!/usr/bin/env bash
# Script that display time for 12 hours and 59 minutes

hours=0
minutes=1
while (( hours <= 12 ));
do
	minutes=1
	echo "Hour: $hours"
	while (( minutes <= 59 ));
	do
		echo "$minutes"
		((minutes++))
	done
	((hours++))
done
