#!/usr/bin/env bash
# let fixes server bug
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
#let kill the running process apache2
pkill apache2
# restart nginx
sudo -u nginx service nginx start
